def register_modules(registry):
    registry.register(
        name = "drivers/soc/qcom/hab/msm_hab",
        out = "msm_hab.ko",
        config = "CONFIG_MSM_HAB",
        srcs = [
            # do not sort
            "drivers/soc/qcom/hab/hab.c",
            "drivers/soc/qcom/hab/hab.h",
            "drivers/soc/qcom/hab/hab_grantable.h",
            "drivers/soc/qcom/hab/hab_linux.c",
            "drivers/soc/qcom/hab/hab_mem_linux.c",
            "drivers/soc/qcom/hab/hab_mimex.c",
            "drivers/soc/qcom/hab/hab_msg.c",
            "drivers/soc/qcom/hab/hab_open.c",
            "drivers/soc/qcom/hab/hab_os.h",
            "drivers/soc/qcom/hab/hab_parser.c",
            "drivers/soc/qcom/hab/hab_pchan.c",
            "drivers/soc/qcom/hab/hab_pipe.c",
            "drivers/soc/qcom/hab/hab_pipe.h",
            "drivers/soc/qcom/hab/hab_qvm.c",
            "drivers/soc/qcom/hab/hab_qvm.h",
            "drivers/soc/qcom/hab/hab_qvm_linux.c",
            "drivers/soc/qcom/hab/hab_qvm_os.h",
            "drivers/soc/qcom/hab/hab_stat.c",
            "drivers/soc/qcom/hab/hab_trace_os.h",
            "drivers/soc/qcom/hab/hab_vchan.c",
            "drivers/soc/qcom/hab/khab.c",
            "drivers/soc/qcom/hab/khab_test.c",
            "drivers/soc/qcom/hab/khab_test.h",
            "drivers/soc/qcom/hab/qvm_comm.c",
            "drivers/soc/qcom/hab/qvm_comm_linux.c",
            "drivers/soc/qcom/hab/hab_virtio.c",
            "drivers/soc/qcom/hab/hab_virtio.h",
            "drivers/soc/qcom/hab/hab_virq.h",
            "drivers/soc/qcom/hab/hab_virq_hgy.h",
            "drivers/soc/qcom/hab/hab_virq.c",
            "drivers/soc/qcom/hab/hab_virq_hgy.c",
        ],
        deps = [
            # do not sort
            "drivers/soc/qcom/hab/hab",
            "drivers/virt/gunyah/gh_dbl",
        ],
    )
