def register_modules(registry):
    registry.register(
        name = "drivers/usb/dwc3/dwc3-msm",
        out = "dwc3-msm.ko",
        config = "CONFIG_USB_DWC3_MSM",
        local_defines = ["OPLUS_FEATURE_CHG_BASIC"],
        srcs = [
            # do not sort
            "drivers/usb/dwc3/debug-ipc.h",
            "drivers/usb/dwc3/debug_ipc.c",
            "drivers/usb/dwc3/dwc3-msm-core.c",
            "drivers/usb/dwc3/dwc3-msm-ops.c",
        ],
        deps = [
            # do not sort
            "drivers/soc/qcom/wcd_usbss_i2c",
            "drivers/usb/typec/ucsi/ucsi_qti_glink",
            "drivers/usb/redriver/redriver",
            "drivers/usb/repeater/repeater",
            "drivers/base/regmap/qti-regmap-debugfs",
            "drivers/soc/qcom/qti_pmic_glink",
            "drivers/soc/qcom/pdr_interface",
            "drivers/soc/qcom/qmi_helpers",
            "drivers/remoteproc/rproc_qcom_common",
            "drivers/rpmsg/qcom_smd",
            "drivers/rpmsg/qcom_glink_smem",
            "drivers/rpmsg/qcom_glink",
            "drivers/clk/qcom/clk-qcom",
            "drivers/clk/qcom/gdsc-regulator",
            "drivers/regulator/debug-regulator",
            "drivers/regulator/proxy-consumer",
            "drivers/soc/qcom/crm-v2",
            "kernel/trace/qcom_ipc_logging",
            "drivers/soc/qcom/minidump",
            "drivers/soc/qcom/smem",
            "drivers/soc/qcom/debug_symbol",
            "drivers/dma-buf/heaps/qcom_dma_heaps",
            "drivers/iommu/msm_dma_iommu_mapping",
            "drivers/soc/qcom/mem_buf/mem_buf_dev",
            "drivers/soc/qcom/secure_buffer",
            "drivers/firmware/qcom/qcom-scm",
            "drivers/virt/gunyah/gh_rm_drv",
            "drivers/virt/gunyah/gh_msgq",
            "drivers/virt/gunyah/gh_dbl",
            "arch/arm64/gunyah/gh_arm_drv",
        ],
    )
