/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#include <linux/bits.h>
#include <linux/bitfield.h>

/* QPACE_CORE_HW_VERSION accessors */
#define QPACE_CORE_HW_VERSION_OFFSET 0x0
#define CORE_HW_VERSION_MAJOR GENMASK(27, 24)
#define CORE_HW_VERSION_MINOR GENMASK(23, 16)
#define CORE_HW_VERSION_REVISION GENMASK(15, 0)

/* QPACE_CORE_QNS4_CFG accessors */
#define QPACE_CORE_QNS4_CFG_OFFSET 0x14
#define CORE_QNS4_CFG_TRTYPE GENMASK(20, 18)
#define CORE_QNS4_CFG_CACHEINDEX GENMASK(17, 12)
#define CORE_QNS4_CFG_CACHEALLOC_WA GENMASK(11, 8)
#define CORE_QNS4_CFG_CACHEALLOC_RF GENMASK(7, 4)
#define CORE_QNS4_CFG_CACHEALLOC_NO_OP GENMASK(3, 0)

/* QPACE_CORE_DMA_TR_n_RESOURCE_CFG accessors */
#define QPACE_CORE_DMA_TR_n_RESOURCE_CFG_OFFSET 0x1c
#define CORE_DMA_TR_n_RESOURCE_C_PRIO GENMASK(29, 28)
#define CORE_DMA_TR_n_RESOURCE_C_DECOMP_BULK_ONLY BIT(25)
#define CORE_DMA_TR_n_RESOURCE_C_COMP_BULK_ONLY BIT(24)
#define CORE_DMA_TR_n_RESOURCE_C_COPY_MAX GENMASK(23, 20)
#define CORE_DMA_TR_n_RESOURCE_C_COPY_MIN GENMASK(19, 16)
#define CORE_DMA_TR_n_RESOURCE_C_DECOMP_MAX GENMASK(15, 12)
#define CORE_DMA_TR_n_RESOURCE_C_DECOMP_MIN GENMASK(11, 8)
#define CORE_DMA_TR_n_RESOURCE_C_COMP_MAX GENMASK(7, 4)
#define CORE_DMA_TR_n_RESOURCE_C_COMP_MIN GENMASK(3, 0)

/* QPACE_CORE_URG_CMD_n_RESOURCE_CFG accessors */
#define QPACE_CORE_URG_CMD_n_RESOURCE_CFG_OFFSET 0x9c
#define CORE_URG_CMD_n_RESOURCE__PRIO GENMASK(29, 28)
#define CORE_URG_CMD_n_RESOURCE__DECOMP_BULK_ONLY BIT(25)
#define CORE_URG_CMD_n_RESOURCE__COMP_BULK_ONLY BIT(24)
#define CORE_URG_CMD_n_RESOURCE__COPY_MAX BIT(20)
#define CORE_URG_CMD_n_RESOURCE__COPY_MIN BIT(16)
#define CORE_URG_CMD_n_RESOURCE__DECOMP_MAX BIT(12)
#define CORE_URG_CMD_n_RESOURCE__DECOMP_MIN BIT(8)
#define CORE_URG_CMD_n_RESOURCE__COMP_MAX BIT(4)
#define CORE_URG_CMD_n_RESOURCE__COMP_MIN BIT(0)

/* QPACE_CORE_OPER_CORE_RUN_STOP accessors */
#define QPACE_CORE_OPER_CORE_RUN_STOP_OFFSET 0x0
#define CORE_OPER_CORE_RUN_STOP_RUN_STOP BIT(0)

/* QPACE_CORE_OPER_CORE_READY accessors */
#define QPACE_CORE_OPER_CORE_READY_OFFSET 0x4
#define CORE_OPER_CORE_READY_READY BIT(0)

/* QPACE_CORE_OPER_CFG accessors */
#define QPACE_CORE_OPER_CFG_OFFSET 0x8
#define CORE_OPER_CFG_MEM_PWR_DWN_HANDSHAKE_DISABLE BIT(6)
#define CORE_OPER_CFG_DECOMP_MEM_PWR_DWN_1 BIT(5)
#define CORE_OPER_CFG_DECOMP_MEM_PWR_DWN_0 BIT(4)
#define CORE_OPER_CFG_COMP_MEM_PWR_DWN_1 BIT(3)
#define CORE_OPER_CFG_COMP_MEM_PWR_DWN_0 BIT(2)
#define CORE_OPER_CFG_STOP2RUN_DECOMP_MEM_INIT_EN BIT(1)
#define CORE_OPER_CFG_PWR_UP_ACK_SW_OVERRIDE BIT(0)

/* QPACE_CORE_OPER_GEN_INTR_STAT accessors */
#define QPACE_CORE_OPER_GEN_INTR_STAT_OFFSET 0x58
#define CORE_OPER_GEN_INTR_STAT_QNS4_HASPLD_0_STAT_RSP BIT(1)
#define CORE_OPER_GEN_INTR_STAT_QNS4_WORD_ERR_STAT BIT(0)

/* QPACE_CORE_OPER_GEN_INTR_EN accessors */
#define QPACE_CORE_OPER_GEN_INTR_EN_OFFSET 0x5c
#define CORE_OPER_GEN_INTR_EN_QNS4_HASPLD_0_STAT_RSP_INTR_EN BIT(1)
#define CORE_OPER_GEN_INTR_EN_QNS4_WORD_ERR_INTR_EN BIT(0)

/* QPACE_CORE_OPER_GEN_INTR_STAT_CLR accessors */
#define QPACE_CORE_OPER_GEN_INTR_STAT_CLR_OFFSET 0x60
#define CORE_OPER_GEN_INTR_STAT__QNS4_HASPLD_0_STAT_RSP_CLR BIT(1)
#define CORE_OPER_GEN_INTR_STAT__QNS4_WORD_ERR_STAT_CLR BIT(0)

/* QPACE_COMP_CORE_CFG accessors */
#define QPACE_COMP_CORE_CFG_OFFSET 0x0
#define COMP_CORE_CFG_PAD_LAST_WITH_ONES_EN BIT(18)
#define COMP_CORE_CFG_DMA_WR_MAX_OT GENMASK(17, 13)
#define COMP_CORE_CFG_DMA_RD_MAX_OT GENMASK(12, 8)
#define COMP_CORE_CFG_HIST_BUFF_INTER_DEPTH GENMASK(6, 4)
#define COMP_CORE_CFG_HIST_BUFF_SRCH_CYCLES GENMASK(3, 0)

/* QPACE_COMP_CORE_BULK_MODE accessors */
#define QPACE_COMP_CORE_BULK_MODE_OFFSET 0x4
#define COMP_CORE_BULK_MODE_RESERVED_7 BIT(7)
#define COMP_CORE_BULK_MODE_RESERVED_6 BIT(6)
#define COMP_CORE_BULK_MODE_RESERVED_5 BIT(5)
#define COMP_CORE_BULK_MODE_CORE_4 BIT(4)
#define COMP_CORE_BULK_MODE_CORE_3 BIT(3)
#define COMP_CORE_BULK_MODE_CORE_2 BIT(2)
#define COMP_CORE_BULK_MODE_CORE_1 BIT(1)
#define COMP_CORE_BULK_MODE_CORE_0 BIT(0)

/* QPACE_DECOMP_CORE_CFG accessors */
#define QPACE_DECOMP_CORE_CFG_OFFSET 0x0
#define DECOMP_CORE_CFG_DECOMP_DMA_MEM_MNG_PAGE_SIZE GENMASK(12, 10)
#define DECOMP_CORE_CFG_DMA_WR_MAX_OT GENMASK(9, 5)
#define DECOMP_CORE_CFG_DMA_RD_MAX_OT GENMASK(4, 0)

/* QPACE_DECOMP_CORE_BULK_MODE accessors */
#define QPACE_DECOMP_CORE_BULK_MODE_OFFSET 0x4
#define DECOMP_CORE_BULK_MODE_RESERVED_7_2 GENMASK(7, 2)
#define DECOMP_CORE_BULK_MODE_CORE_1 BIT(1)
#define DECOMP_CORE_BULK_MODE_CORE_0 BIT(0)

/* QPACE_URG_CMD_0_TD_DST_ADDR_L_CFG_CNTXT accessors */
#define QPACE_URG_CMD_0_TD_DST_ADDR_L_CFG_CNTXT_OFFSET 0x0
#define URG_CMD_0_TD_DST_ADDR_L__DST_ADDR_L GENMASK(31, 8)
#define URG_CMD_0_TD_DST_ADDR_L__CMD_CFG_CNTXT GENMASK(3, 0)

/* QPACE_URG_CMD_0_TD_DST_ADDR_H accessors */
#define QPACE_URG_CMD_0_TD_DST_ADDR_H_OFFSET 0x4
#define URG_CMD_0_TD_DST_ADDR_H_DST_ADDR_H GENMASK(31, 0)

/* QPACE_URG_CMD_0_TD_SRC_ADDR_L accessors */
#define QPACE_URG_CMD_0_TD_SRC_ADDR_L_OFFSET 0x8
#define URG_CMD_0_TD_SRC_ADDR_L_SRC_ADDR_L GENMASK(31, 0)

/* QPACE_URG_CMD_0_TD_SRC_ADDR_H accessors */
#define QPACE_URG_CMD_0_TD_SRC_ADDR_H_OFFSET 0xc
#define URG_CMD_0_TD_SRC_ADDR_H_SRC_ADDR_H GENMASK(31, 0)

/* QPACE_URG_CMD_0_ED_ADDR_L accessors */
#define QPACE_URG_CMD_0_ED_ADDR_L_OFFSET 0x10
#define URG_CMD_0_ED_ADDR_L_ADDR_L GENMASK(31, 0)

/* QPACE_URG_CMD_0_ED_ADDR_H accessors */
#define QPACE_URG_CMD_0_ED_ADDR_H_OFFSET 0x14
#define URG_CMD_0_ED_ADDR_H_ADDR_H GENMASK(31, 0)

/* QPACE_URG_CMD_0_ED_STAT accessors */
#define QPACE_URG_CMD_0_ED_STAT_OFFSET 0x18
#define URG_CMD_0_ED_STAT_RF BIT(31)
#define URG_CMD_0_ED_STAT_COMP_CODE GENMASK(23, 20)
#define URG_CMD_0_ED_STAT_SIZE GENMASK(19, 0)

/* QPACE_URG_CMD_0_ED_REP_WORD accessors */
#define QPACE_URG_CMD_0_ED_REP_WORD_OFFSET 0x1c
#define URG_CMD_0_ED_REP_WORD_REP_WORD GENMASK(31, 0)

/* QPACE_URG_CMD_0_ED_CRC accessors */
#define QPACE_URG_CMD_0_ED_CRC_OFFSET 0x20
#define URG_CMD_0_ED_CRC_CRC GENMASK(31, 0)

/* QPACE_URG_CMD_0_STAT accessors */
#define QPACE_URG_CMD_0_STAT_OFFSET 0x24
#define URG_CMD_0_STAT_REQ_ON_ACTIVE_ERR BIT(1)
#define URG_CMD_0_STAT_ACTIVE BIT(0)

/* QPACE_URG_CMD_0_STAT_CLR accessors */
#define QPACE_URG_CMD_0_STAT_CLR_OFFSET 0x28
#define URG_CMD_0_STAT_CLR_REQ_ON_ACTIVE_ERR BIT(1)

/* QPACE_URG_CMD_0_CFG_CNTXT_SIZE_n accessors */
#define QPACE_URG_CMD_0_CFG_CNTXT_SIZE_n_OFFSET 0x40
#define URG_CMD_0_CFG_CNTXT_SIZE_SIZE GENMASK(19, 0)

/* QPACE_URG_CMD_0_CFG_CNTXT_CRC_n accessors */
#define QPACE_URG_CMD_0_CFG_CNTXT_CRC_n_OFFSET 0x44
#define URG_CMD_0_CFG_CNTXT_CRC__CRC GENMASK(31, 0)

/* QPACE_URG_CMD_0_CFG_CNTXT_MISC_n accessors */
#define QPACE_URG_CMD_0_CFG_CNTXT_MISC_n_OFFSET 0x48
#define URG_CMD_0_CFG_CNTXT_MISC_PCD BIT(30)
#define URG_CMD_0_CFG_CNTXT_MISC_WA BIT(21)
#define URG_CMD_0_CFG_CNTXT_MISC_RF BIT(20)
#define URG_CMD_0_CFG_CNTXT_MISC_DCTX GENMASK(17, 16)
#define URG_CMD_0_CFG_CNTXT_MISC_SCTX GENMASK(15, 14)
#define URG_CMD_0_CFG_CNTXT_MISC_PAGE_CNT GENMASK(13, 8)
#define URG_CMD_0_CFG_CNTXT_MISC_OPER GENMASK(6, 4)
#define URG_CMD_0_CFG_CNTXT_MISC_PCM BIT(3)
#define URG_CMD_0_CFG_CNTXT_MISC_CK BIT(2)
#define URG_CMD_0_CFG_CNTXT_MISC_CM BIT(1)
#define URG_CMD_0_CFG_CNTXT_MISC_CE BIT(0)

/* QPACE_URG_CMD_0_DMA_RD_ERR accessors */
#define QPACE_URG_CMD_0_DMA_RD_ERR_OFFSET 0x1e0
#define URG_CMD_0_DMA_RD_ERR_DMA_RD_ERR_CODE GENMASK(6, 4)
#define URG_CMD_0_DMA_RD_ERR_DMA_RD_ERR_DET BIT(0)

/* QPACE_URG_CMD_0_DMA_WR_ERR accessors */
#define QPACE_URG_CMD_0_DMA_WR_ERR_OFFSET 0x1e8
#define URG_CMD_0_DMA_WR_ERR_DMA_WR_ERR_CODE GENMASK(6, 4)
#define URG_CMD_0_DMA_WR_ERR_DMA_WR_ERR_DET BIT(0)

/* QPACE_DMA_TR_MGR_0_START_L accessors */
#define QPACE_DMA_TR_MGR_0_START_L_OFFSET 0x0
#define DMA_TR_MGR_0_START_L_RING_START_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_START_H accessors */
#define QPACE_DMA_TR_MGR_0_START_H_OFFSET 0x4
#define DMA_TR_MGR_0_START_H_RING_START_H GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_END_L accessors */
#define QPACE_DMA_TR_MGR_0_END_L_OFFSET 0x8
#define DMA_TR_MGR_0_END_L_RING_END_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_END_H accessors */
#define QPACE_DMA_TR_MGR_0_END_H_OFFSET 0xc
#define DMA_TR_MGR_0_END_H_RING_END_H GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_WR_PTR_L accessors */
#define QPACE_DMA_TR_MGR_0_WR_PTR_L_OFFSET 0x10
#define DMA_TR_MGR_0_WR_PTR_L_WR_PTR_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_WR_PTR_H accessors */
#define QPACE_DMA_TR_MGR_0_WR_PTR_H_OFFSET 0x14
#define DMA_TR_MGR_0_WR_PTR_H_WR_PTR_H GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_RD_PTR_L accessors */
#define QPACE_DMA_TR_MGR_0_RD_PTR_L_OFFSET 0x18
#define DMA_TR_MGR_0_RD_PTR_L_RD_PTR_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_RD_PTR_H accessors */
#define QPACE_DMA_TR_MGR_0_RD_PTR_H_OFFSET 0x1c
#define DMA_TR_MGR_0_RD_PTR_H_RD_PTR_H GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_CFG accessors */
#define QPACE_DMA_TR_MGR_0_CFG_OFFSET 0x20
#define DMA_TR_MGR_0_CFG_COMP_SIZE_OVER_LIMIT_FORCE_EVT BIT(6)
#define DMA_TR_MGR_0_CFG_CTX GENMASK(5, 4)
#define DMA_TR_MGR_0_CFG_CACHEALLOC GENMASK(3, 0)

/* QPACE_DMA_TR_MGR_0_TD_RD_ERR accessors */
#define QPACE_DMA_TR_MGR_0_TD_RD_ERR_OFFSET 0x30
#define DMA_TR_MGR_0_TD_RD_ERR_TD_RD_ERR_CODE GENMASK(6, 4)
#define DMA_TR_MGR_0_TD_RD_ERR_TD_RD_ERR_DET BIT(0)

/* QPACE_DMA_TR_MGR_0_DMA_RD_ERR accessors */
#define QPACE_DMA_TR_MGR_0_DMA_RD_ERR_OFFSET 0x34
#define DMA_TR_MGR_0_DMA_RD_ERR_DMA_RD_ERR_CODE GENMASK(6, 4)
#define DMA_TR_MGR_0_DMA_RD_ERR_DMA_RD_ERR_DET BIT(0)

/* QPACE_DMA_TR_MGR_0_DMA_RD_ERR_TD_ADDR_L accessors */
#define QPACE_DMA_TR_MGR_0_DMA_RD_ERR_TD_ADDR_L_OFFSET 0x38
#define DMA_TR_MGR_0_DMA_RD_ERR__DMA_RD_ERR_TD_ADDR_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_DMA_RD_ERR_TD_ADDR_H accessors */
#define QPACE_DMA_TR_MGR_0_DMA_RD_ERR_TD_ADDR_H_OFFSET 0x3c
#define DMA_TR_MGR_0_DMA_RD_ERR__DMA_RD_ERR_TD_ADDR_H GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_DMA_WR_ERR accessors */
#define QPACE_DMA_TR_MGR_0_DMA_WR_ERR_OFFSET 0x44
#define DMA_TR_MGR_0_DMA_WR_ERR_DMA_WR_ERR_CODE GENMASK(6, 4)
#define DMA_TR_MGR_0_DMA_WR_ERR_DMA_WR_ERR_DET BIT(0)

/* QPACE_DMA_TR_MGR_0_DMA_WR_ERR_TD_ADDR_L accessors */
#define QPACE_DMA_TR_MGR_0_DMA_WR_ERR_TD_ADDR_L_OFFSET 0x48
#define DMA_TR_MGR_0_DMA_WR_ERR__DMA_WR_ERR_TD_ADDR_L GENMASK(31, 0)

/* QPACE_DMA_TR_MGR_0_DMA_WR_ERR_TD_ADDR_H accessors */
#define QPACE_DMA_TR_MGR_0_DMA_WR_ERR_TD_ADDR_H_OFFSET 0x4c
#define DMA_TR_MGR_0_DMA_WR_ERR__DMA_WR_ERR_TD_ADDR_H GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_START_L accessors */
#define QPACE_DMA_ER_MGR_0_START_L_OFFSET 0x0
#define DMA_ER_MGR_0_START_L_RING_START_L GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_START_H accessors */
#define QPACE_DMA_ER_MGR_0_START_H_OFFSET 0x4
#define DMA_ER_MGR_0_START_H_RING_START_H GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_END_L accessors */
#define QPACE_DMA_ER_MGR_0_END_L_OFFSET 0x8
#define DMA_ER_MGR_0_END_L_RING_END_L GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_END_H accessors */
#define QPACE_DMA_ER_MGR_0_END_H_OFFSET 0xc
#define DMA_ER_MGR_0_END_H_RING_END_H GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_WR_PTR_L accessors */
#define QPACE_DMA_ER_MGR_0_WR_PTR_L_OFFSET 0x10
#define DMA_ER_MGR_0_WR_PTR_L_WR_PTR_L GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_WR_PTR_H accessors */
#define QPACE_DMA_ER_MGR_0_WR_PTR_H_OFFSET 0x14
#define DMA_ER_MGR_0_WR_PTR_H_WR_PTR_H GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_RD_PTR_L accessors */
#define QPACE_DMA_ER_MGR_0_RD_PTR_L_OFFSET 0x18
#define DMA_ER_MGR_0_RD_PTR_L_RD_PTR_L GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_RD_PTR_H accessors */
#define QPACE_DMA_ER_MGR_0_RD_PTR_H_OFFSET 0x1c
#define DMA_ER_MGR_0_RD_PTR_H_RD_PTR_H GENMASK(31, 0)

/* QPACE_DMA_ER_MGR_0_CFG accessors */
#define QPACE_DMA_ER_MGR_0_CFG_OFFSET 0x20
#define DMA_ER_MGR_0_CFG_CTX GENMASK(5, 4)
#define DMA_ER_MGR_0_CFG_CACHEALLOC GENMASK(3, 0)

/* QPACE_DMA_ER_MGR_0_ED_WR_ERR accessors */
#define QPACE_DMA_ER_MGR_0_ED_WR_ERR_OFFSET 0x30
#define DMA_ER_MGR_0_ED_WR_ERR_ED_WR_ERR_CODE GENMASK(6, 4)
#define DMA_ER_MGR_0_ED_WR_ERR_ED_WR_ERR_DET BIT(0)

/* QPACE_COMMON_EE_URG_CMD_COMPL_STAT accessors */
#define QPACE_COMMON_EE_URG_CMD_COMPL_STAT_OFFSET 0x0
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_7_COMPL_STAT BIT(7)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_6_COMPL_STAT BIT(6)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_5_COMPL_STAT BIT(5)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_4_COMPL_STAT BIT(4)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_3_COMPL_STAT BIT(3)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_2_COMPL_STAT BIT(2)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_1_COMPL_STAT BIT(1)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_0_COMPL_STAT BIT(0)

/* QPACE_COMMON_EE_URG_CMD_COMPL_INTR_EN accessors */
#define QPACE_COMMON_EE_URG_CMD_COMPL_INTR_EN_OFFSET 0x4
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_7_COMPL_INTR_EN BIT(7)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_6_COMPL_INTR_EN BIT(6)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_5_COMPL_INTR_EN BIT(5)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_4_COMPL_INTR_EN BIT(4)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_3_COMPL_INTR_EN BIT(3)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_2_COMPL_INTR_EN BIT(2)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_1_COMPL_INTR_EN BIT(1)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_0_COMPL_INTR_EN BIT(0)

/* QPACE_COMMON_EE_URG_CMD_COMPL_STAT_CLR accessors */
#define QPACE_COMMON_EE_URG_CMD_COMPL_STAT_CLR_OFFSET 0x8
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_7_COMPL_STAT_CLR BIT(7)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_6_COMPL_STAT_CLR BIT(6)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_5_COMPL_STAT_CLR BIT(5)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_4_COMPL_STAT_CLR BIT(4)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_3_COMPL_STAT_CLR BIT(3)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_2_COMPL_STAT_CLR BIT(2)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_1_COMPL_STAT_CLR BIT(1)
#define COMMON_EE_URG_CMD_COMPL__URG_CMD_0_COMPL_STAT_CLR BIT(0)

/* QPACE_COMMON_EE_DMA_ER_COMPL_STAT accessors */
#define QPACE_COMMON_EE_DMA_ER_COMPL_STAT_OFFSET 0xc
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_BUS_ERR_STAT BIT(31)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_TR_BUS_ERR_STAT BIT(30)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_7_COMPL_STAT BIT(7)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_6_COMPL_STAT BIT(6)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_5_COMPL_STAT BIT(5)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_4_COMPL_STAT BIT(4)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_3_COMPL_STAT BIT(3)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_2_COMPL_STAT BIT(2)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_1_COMPL_STAT BIT(1)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_0_COMPL_STAT BIT(0)

/* QPACE_COMMON_EE_DMA_ER_COMPL_INTR_EN accessors */
#define QPACE_COMMON_EE_DMA_ER_COMPL_INTR_EN_OFFSET 0x10
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_7_COMPL_INTR_EN BIT(7)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_6_COMPL_INTR_EN BIT(6)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_5_COMPL_INTR_EN BIT(5)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_4_COMPL_INTR_EN BIT(4)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_3_COMPL_INTR_EN BIT(3)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_2_COMPL_INTR_EN BIT(2)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_1_COMPL_INTR_EN BIT(1)
#define COMMON_EE_DMA_ER_COMPL_I_DMA_ER_0_COMPL_INTR_EN BIT(0)

/* QPACE_COMMON_EE_DMA_ER_COMPL_STAT_CLR accessors */
#define QPACE_COMMON_EE_DMA_ER_COMPL_STAT_CLR_OFFSET 0x14
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_7_COMPL_STAT_CLR BIT(7)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_6_COMPL_STAT_CLR BIT(6)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_5_COMPL_STAT_CLR BIT(5)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_4_COMPL_STAT_CLR BIT(4)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_3_COMPL_STAT_CLR BIT(3)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_2_COMPL_STAT_CLR BIT(2)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_1_COMPL_STAT_CLR BIT(1)
#define COMMON_EE_DMA_ER_COMPL_S_DMA_ER_0_COMPL_STAT_CLR BIT(0)

/* QPACE_COMMON_EE_DMA_TR_BUS_ERR_STAT accessors */
#define QPACE_COMMON_EE_DMA_TR_BUS_ERR_STAT_OFFSET 0x18
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_7_BUS_ERR_STAT BIT(7)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_6_BUS_ERR_STAT BIT(6)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_5_BUS_ERR_STAT BIT(5)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_4_BUS_ERR_STAT BIT(4)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_3_BUS_ERR_STAT BIT(3)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_2_BUS_ERR_STAT BIT(2)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_1_BUS_ERR_STAT BIT(1)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_0_BUS_ERR_STAT BIT(0)

/* QPACE_COMMON_EE_DMA_TR_BUS_ERR_INTR_EN accessors */
#define QPACE_COMMON_EE_DMA_TR_BUS_ERR_INTR_EN_OFFSET 0x1c
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_7_BUS_ERR_INTR_EN BIT(7)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_6_BUS_ERR_INTR_EN BIT(6)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_5_BUS_ERR_INTR_EN BIT(5)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_4_BUS_ERR_INTR_EN BIT(4)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_3_BUS_ERR_INTR_EN BIT(3)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_2_BUS_ERR_INTR_EN BIT(2)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_1_BUS_ERR_INTR_EN BIT(1)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_0_BUS_ERR_INTR_EN BIT(0)

/* QPACE_COMMON_EE_DMA_TR_BUS_ERR_STAT_CLR accessors */
#define QPACE_COMMON_EE_DMA_TR_BUS_ERR_STAT_CLR_OFFSET 0x20
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_7_BUS_ERR_STAT_CLR BIT(7)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_6_BUS_ERR_STAT_CLR BIT(6)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_5_BUS_ERR_STAT_CLR BIT(5)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_4_BUS_ERR_STAT_CLR BIT(4)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_3_BUS_ERR_STAT_CLR BIT(3)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_2_BUS_ERR_STAT_CLR BIT(2)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_1_BUS_ERR_STAT_CLR BIT(1)
#define COMMON_EE_DMA_TR_BUS_ERR_DMA_TR_0_BUS_ERR_STAT_CLR BIT(0)

/* QPACE_COMMON_EE_DMA_ER_BUS_ERR_STAT accessors */
#define QPACE_COMMON_EE_DMA_ER_BUS_ERR_STAT_OFFSET 0x24
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_7_BUS_ERR_STAT BIT(7)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_6_BUS_ERR_STAT BIT(6)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_5_BUS_ERR_STAT BIT(5)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_4_BUS_ERR_STAT BIT(4)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_3_BUS_ERR_STAT BIT(3)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_2_BUS_ERR_STAT BIT(2)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_1_BUS_ERR_STAT BIT(1)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_0_BUS_ERR_STAT BIT(0)

/* QPACE_COMMON_EE_DMA_ER_BUS_ERR_INTR_EN accessors */
#define QPACE_COMMON_EE_DMA_ER_BUS_ERR_INTR_EN_OFFSET 0x28
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_7_BUS_ERR_INTR_EN BIT(7)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_6_BUS_ERR_INTR_EN BIT(6)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_5_BUS_ERR_INTR_EN BIT(5)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_4_BUS_ERR_INTR_EN BIT(4)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_3_BUS_ERR_INTR_EN BIT(3)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_2_BUS_ERR_INTR_EN BIT(2)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_1_BUS_ERR_INTR_EN BIT(1)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_0_BUS_ERR_INTR_EN BIT(0)

/* QPACE_COMMON_EE_DMA_ER_BUS_ERR_STAT_CLR accessors */
#define QPACE_COMMON_EE_DMA_ER_BUS_ERR_STAT_CLR_OFFSET 0x2c
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_7_BUS_ERR_STAT_CLR BIT(7)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_6_BUS_ERR_STAT_CLR BIT(6)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_5_BUS_ERR_STAT_CLR BIT(5)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_4_BUS_ERR_STAT_CLR BIT(4)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_3_BUS_ERR_STAT_CLR BIT(3)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_2_BUS_ERR_STAT_CLR BIT(2)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_1_BUS_ERR_STAT_CLR BIT(1)
#define COMMON_EE_DMA_ER_BUS_ERR_DMA_ER_0_BUS_ERR_STAT_CLR BIT(0)
