/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef __DT_BINDINGS_MAILBOX_IPCC_VIENNA_H
#define __DT_BINDINGS_MAILBOX_IPCC_VIENNA_H

/* Physical client IDs */
#define IPCC_MPROC_AOP			0
#define IPCC_MPROC_APSS_S		1
#define IPCC_MPROC_MPSS			2
#define IPCC_MPROC_LPASS		3
#define IPCC_MPROC_CDSP			4
#define IPCC_MPROC_APSS_NS0		5
#define IPCC_MPROC_APSS_NS1		6
#define IPCC_MPROC_APSS_NS2		7
#define IPCC_MPROC_APSS_NS3		8
#define IPCC_MPROC_DUMMY		9
#define IPCC_MPROC_DCP			10
#define IPCC_MPROC_TMESS		11
#define IPCC_MPROC_M55_WM		12
#define IPCC_MPROC_M55_AM		13

#define IPCC_COMPUTE_L0_MPSS		0
#define IPCC_COMPUTE_L0_LAPSS		1
#define IPCC_COMPUTE_L0_CDSP		2
#define IPCC_COMPUTE_L0_APSS_NSO	3
#define IPCC_COMPUTE_L0_GPU0		4
#define IPCC_COMPUTE_L0_APSS_NS1	5
#define IPCC_COMPUTE_L0_APSS_NS2	6
#define IPCC_COMPUTE_L0_APSS_NS3	7
#define IPCC_COMPUTE_L0_VPU		8
#define IPCC_COMPUTE_L0_IPA		9
#define IPCC_COMPUTE_L0_DUMMY		10
#define IPCC_COMPUTE_L0_DCP		11

#define IPCC_COMPUTE_L1_MPSS		0
#define IPCC_COMPUTE_L1_LAPSS		1
#define IPCC_COMPUTE_L1_CDSP		2
#define IPCC_COMPUTE_L1_APSS_NSO	3
#define IPCC_COMPUTE_L1_GPU0		4
#define IPCC_COMPUTE_L1_APSS_NS1	5
#define IPCC_COMPUTE_L1_APSS_NS2	6
#define IPCC_COMPUTE_L1_APSS_NS3	7
#define IPCC_COMPUTE_L1_VPU		8
#define IPCC_COMPUTE_L1_IPA		9
#define IPCC_COMPUTE_L1_DUMMY		10
#define IPCC_COMPUTE_L1_DCP		11


#define IPCC_PERIPH_MPSS	0
#define IPCC_PERIPH_LAPSS	1
#define IPCC_PERIPH_CDSP	2
#define IPCC_PERIPH_APSS_NS0	3
#define IPCC_PERIPH_PCIE0	4
#define IPCC_PERIPH_APSS_NS1	5
#define IPCC_PERIPH_APSS_NS2	6
#define IPCC_PERIPH_APSS_NS3	7
#define IPCC_PERIPH_DUMMY	8

#define IPCC_FENCE_MPSS		0
#define IPCC_FENCE_LAPSS	1
#define IPCC_FENCE_CDSP		2
#define IPCC_FENCE_APSS_NS0	3
#define IPCC_FENCE_APSS_NS1	4
#define IPCC_FENCE_APSS_NS2	5
#define IPCC_FENCE_APSS_NS3	6
#define IPCC_FENCE_IPA		7
#define IPCC_FENCE_DUMMY	8
#define IPCC_FENCE_DCP		9

#endif
