load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load(":oplus_modules_define.bzl", "oplus_ddk_get_oplus_features")

def define_oplus_ddk_modules(target, msm_target, variant):
    oplus_ddk_targets = [
        "//vendor/oplus/hardware/radio/kernel:oplus_mdmfeature",
        "//vendor/oplus/hardware/radio/mdmrst/bazel:oplus_mdmrst",
        "//vendor/oplus/kernel/boot:buildvariant",
        "//vendor/oplus/kernel/boot:cdt_integrity",
        "//vendor/oplus/kernel/boot:oplus_bsp_boot_projectinfo",
        "//vendor/oplus/kernel/boot:oplus_bsp_bootloader_log",
        "//vendor/oplus/kernel/boot:oplus_bsp_bootmode",
        "//vendor/oplus/kernel/boot:oplus_bsp_dfr_kmsg_wb",
        "//vendor/oplus/kernel/boot:oplus_bsp_dfr_phoenix",
        "//vendor/oplus/kernel/boot:oplus_bsp_dfr_qcom_enhance_watchdog",
        "//vendor/oplus/kernel/boot:oplus_bsp_dfr_reboot_speed",
        "//vendor/oplus/kernel/boot:oplus_bsp_dfr_shutdown_speed",
        "//vendor/oplus/kernel/boot:oplus_charger_present",
        "//vendor/oplus/kernel/boot:oplus_ftm_mode",
        "//vendor/oplus/kernel/boot:oplusboot",
        "//vendor/oplus/kernel/boot:saupwk",
        "//vendor/oplus/kernel/boot:tango32",
        "//vendor/oplus/kernel/camera:{}_camera_extension".format(target),
        "//vendor/oplus/kernel/charger/bazel:{}_oplus_cfg".format(target),
        "//vendor/oplus/kernel/charger/bazel:{}_oplus_chg_v2".format(target),
        "//vendor/oplus/kernel/charger/bazel:{}_test-kit".format(target),
        "//vendor/oplus/kernel/charger/bazel:{}_ufcs_class".format(target),
        "//vendor/oplus/kernel/cpu:cpufreq_bouncing",
        "//vendor/oplus/kernel/cpu:horae_shell_temp",
        "//vendor/oplus/kernel/cpu:oplus_bsp_frame_boost",
        "//vendor/oplus/kernel/cpu:oplus_bsp_sched_ext",
        "//vendor/oplus/kernel/cpu:oplus_bsp_game_opt",
        "//vendor/oplus/kernel/cpu:oplus_bsp_geas_cpu",
        "//vendor/oplus/kernel/cpu:oplus_bsp_geas_system",
        "//vendor/oplus/kernel/cpu:oplus_bsp_midas",
        "//vendor/oplus/kernel/cpu:oplus_bsp_sched_assist",
        "//vendor/oplus/kernel/cpu:oplus_bsp_schedinfo",
        "//vendor/oplus/kernel/cpu:oplus_bsp_task_cpustats",
        "//vendor/oplus/kernel/cpu:oplus_bsp_task_load",
        "//vendor/oplus/kernel/cpu:oplus_bsp_task_overload",
        "//vendor/oplus/kernel/cpu:oplus_bsp_task_sched",
        "//vendor/oplus/kernel/cpu:oplus_bsp_waker_identify",
        "//vendor/oplus/kernel/cpu:oplus_freqqos_monitor",
        "//vendor/oplus/kernel/cpu:osml_monitor",
        "//vendor/oplus/kernel/cpu:ua_cpu_ioctl",
        "//vendor/oplus/kernel/device_info/device_info/bazel:device_info",
        "//vendor/oplus/kernel/device_info/magnetic_cover:oplus_magcvr_ak09973",
        "//vendor/oplus/kernel/device_info/magnetic_cover:oplus_magcvr_mkh100a",
        "//vendor/oplus/kernel/device_info/magnetic_cover:oplus_magcvr_mxm1120",
        "//vendor/oplus/kernel/device_info/magnetic_cover:oplus_magnetic_cover",
        "//vendor/oplus/kernel/device_info/magtransfer:oplus_magcvr_notify",
        "//vendor/oplus/kernel/dfr:mtk_wdt",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_combkey_monitor",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_dump_device_info",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_dump_reason",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_fdleak_check",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_force_shutdown",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_hung_task_enhance",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_init_watchdog",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_keyevent_handler",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_kp_freeze_detect",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_last_boot_reason",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_ordump",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_pmic_monitor",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_pmic_watchdog",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_shutdown_detect",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_theia",
        "//vendor/oplus/kernel/dfr:oplus_bsp_dfr_ubt",
        "//vendor/oplus/kernel/dft/bazel:oplus_bsp_dft_kernel_fb",
        "//vendor/oplus/kernel/dft/bazel:oplus_bsp_dft_olc",
        "//vendor/oplus/kernel/framework_stability/oplus_stability_helper:oplus_sys_stability_helper",
        "//vendor/oplus/kernel/graphics:oplus_sync_fence",
        "//vendor/oplus/kernel/hans:oplus_sys_hans",
        "//vendor/oplus/kernel/ipc:oplus_binder_strategy",
        "//vendor/oplus/kernel/mm:oplus_bsp_dynamic_readahead",
        "//vendor/oplus/kernel/mm:oplus_bsp_kshrink_slabd",
        "//vendor/oplus/kernel/mm:oplus_bsp_kswapd_opt",
        "//vendor/oplus/kernel/mm:oplus_bsp_memleak_detect",
        "//vendor/oplus/kernel/mm:oplus_bsp_zstdn",
        "//vendor/oplus/kernel/mm:oplus_bsp_mm_osvelte",
        "//vendor/oplus/kernel/mm:oplus_bsp_pcppages_opt",
        "//vendor/oplus/kernel/mm:oplus_bsp_proactive_compact",
        "//vendor/oplus/kernel/mm:oplus_bsp_sigkill_diagnosis",
        "//vendor/oplus/kernel/mm:oplus_bsp_uxmem_opt",
        "//vendor/oplus/kernel/mm:oplus_bsp_zram_opt",
        "//vendor/oplus/kernel/multimedia/feedback/bazel:oplus_mm_kevent",
        "//vendor/oplus/kernel/multimedia/feedback/bazel:oplus_mm_kevent_fb",
        "//vendor/oplus/kernel/network:oplus_network_app_monitor",
        "//vendor/oplus/kernel/network:oplus_network_data_module",
        "//vendor/oplus/kernel/network:oplus_network_dns_hook",
        "//vendor/oplus/kernel/network:oplus_network_esim",
        "//vendor/oplus/kernel/network:oplus_network_game_first",
        "//vendor/oplus/kernel/network:oplus_network_linkpower_module",
        "//vendor/oplus/kernel/network:oplus_network_oem_qmi",
        "//vendor/oplus/kernel/network:oplus_network_qr_scan",
        "//vendor/oplus/kernel/network:oplus_network_rf_cable_monitor",
        "//vendor/oplus/kernel/network:oplus_network_score",
        "//vendor/oplus/kernel/network:oplus_network_sim_detect",
        "//vendor/oplus/kernel/network:oplus_network_stats_calc",
        "//vendor/oplus/kernel/network:oplus_network_tuning",
        "//vendor/oplus/kernel/network:oplus_network_vnet",
        "//vendor/oplus/kernel/power/power_hook:oplus_power_hook",
        "//vendor/oplus/kernel/power/rpmh:oplus_rpmh_statics",
        "//vendor/oplus/kernel/power/standby_netlink:oplus_standby_netlink",
        "//vendor/oplus/kernel/secureguard/gki2.0/rootguard_new:oplus_secure_guard_new",
        "//vendor/oplus/kernel/storage:oplus_bsp_storage_io_metrics",
        "//vendor/oplus/kernel/storage:oplus_uprobe",
        "//vendor/oplus/kernel/storage:oplus_wq_dynamic_priority",
        "//vendor/oplus/kernel/storage:storage_log",
        "//vendor/oplus/kernel/storage:ufs-oplus-dbg",
        "//vendor/oplus/kernel/storage:oplus_file_record",
        "//vendor/oplus/kernel/storage/oplus_overlayfs:oplus_overlay",
        "//vendor/oplus/kernel/synchronize:oplus_lock_torture",
        "//vendor/oplus/kernel/synchronize:oplus_locking_strategy",
        "//vendor/oplus/kernel/touchpanel/kernelFwUpdate/bazel:oplus_bsp_fw_update",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_common",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_custom",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_focal_common",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ft3518",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ft3658u_spi",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ft3681",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ft3683g",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ft8057p",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_goodix_comnon",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_gt9916",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_gt9966",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ilitek7807s",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_ilitek_common",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_novatek_common",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_nt36528_noflash",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_nt36532_noflash",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_nt36536_noflash",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_nt36672c_noflash",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_syna_common",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_tcm_S3908",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_tcm_S3910",
        "//vendor/oplus/kernel/touchpanel/oplus_touchscreen_v2:oplus_bsp_tp_td4377_noflash",
        "//vendor/oplus/kernel/touchpanel/synaptics_hbp:oplus_bsp_synaptics_tcm2",
        "//vendor/oplus/kernel/touchpanel/touchpanel_notify/bazel:oplus_bsp_tp_notify",
        "//vendor/oplus/kernel/tp/hbp/hbp:oplus_bsp_tp_hbp_goodix_gt99x6",
        "//vendor/oplus/kernel/tp/hbp/hbp:oplus_bsp_tp_hbp_syna_s3910",
        "//vendor/oplus/kernel/tp/hbp/hbp:oplus_ft3683g",
        "//vendor/oplus/kernel/tp/hbp/hbp:oplus_hbp_core",
        "//vendor/oplus/kernel/vibrator/bazel:oplus_bsp_haptic",
        "//vendor/oplus/kernel/vibrator/bazel:oplus_bsp_haptic_feedback",
        "//vendor/oplus/kernel/wifi:oplus_connectivity_routerboost",
        "//vendor/oplus/kernel/wifi:oplus_connectivity_sla",
        "//vendor/oplus/kernel/wifi:oplus_wifi_wsa",
        "//vendor/oplus/kernel/wifi:oplus_wificapcenter",
        "//vendor/oplus/secure/biometrics/fingerprints/bsp/uff/driver:oplus_bsp_uff_fp_driver",
        "//vendor/oplus/secure/common/bsp/drivers/oplus_secure_common:oplus_secure_common",
        "//vendor/oplus/sensor/kernel/qcom:oplus_sensor_deviceinfo",
        "//vendor/oplus/sensor/kernel/qcom:oplus_sensor_feedback",
        "//vendor/oplus/sensor/kernel/qcom:oplus_sensor_interact",
        "//vendor/oplus/sensor/kernel/qcom:oplus_sensor_ir_core",
        "//vendor/oplus/sensor/kernel/qcom:oplus_sensor_kookong_ir_spi",
        "//vendor/oplus/kernel/nfc:oplus_nfc",
        "//vendor/oplus/kernel/nfc:oplus_network_nfc_thn31",
        "//vendor/oplus/kernel/patch:oplus_patch",
    ]

    if "canoe" in str(target) :
        oplus_ddk_targets += [
            "//vendor/oplus/kernel/wifi:wonder",
        ]

    #conditional_build modules
    oplus_feature_list = oplus_ddk_get_oplus_features()
    if str(oplus_feature_list.get("OPLUS_FEATURE_BSP_DRV_INJECT_TEST", 'foo')).upper() == "1":
        oplus_ddk_targets += [
            "//vendor/oplus/sensor/kernel/qcom:pseudo_sensor",
            "//vendor/oplus/kernel/dfr:oplus_inject_aw8692x",
            "//vendor/oplus/kernel/dfr:oplus_inject",
        ]

    pkg_files(
        name = "{}_all_oplus_ddk_modules_files".format(target),
        srcs = oplus_ddk_targets,
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )
    pkg_install(
        name = "{}_all_oplus_ddk_modules_dist".format(target),
        srcs = [":{}_all_oplus_ddk_modules_files".format(target)],
        destdir = "../device/qcom/canoe-kernel/oplus_ddk",
    )
