# SPDX-License-Identifier: GPL-2.0

"""
Macros to define rules for sources which we want to take directly from ACK.

These files are very lightly modified or built exactly from ACK and aren't
suitable to be system_dlkm modules. We cannot reference them directly in DDK
module sources due to DDK limitations that exist today.
"""

load("@bazel_skylib//rules:copy_file.bzl", "copy_file")

COPY_FILES = [
    "drivers/leds/trigger/ledtrig-pattern.c",
    "drivers/char/virtio_console.c",
    "drivers/dma/qcom/gpi.c",
    "drivers/dma/dmaengine.h",
    "drivers/dma/virt-dma.h",
    "drivers/i2c/busses/i2c-qcom-geni.c",
    "drivers/spi/spi-geni-qcom.c",
    "drivers/virtio/virtio_input.c",
    "net/core/failover.c",
    "lib/crc-itu-t.c",
    "drivers/net/net_failover.c",
    "drivers/net/virtio_net.c",
    "drivers/net/pcs/pcs-xpcs.c",
    "drivers/net/pcs/pcs-xpcs.h",
    "drivers/net/pcs/pcs-xpcs-nxp.c",
    "drivers/net/pcs/pcs-xpcs-plat.c",
    "drivers/net/pcs/pcs-xpcs-wx.c",
    "drivers/net/phy/aquantia/aquantia_leds.c",
    "drivers/net/phy/aquantia/aquantia_firmware.c",
    # cfg80211.ko files start
    "net/wireless/ap.c",
    "net/wireless/certs/sforshee.hex",
    "net/wireless/certs/wens.hex",
    "net/wireless/chan.c",
    "net/wireless/core.c",
    "net/wireless/core.h",
    "net/wireless/debugfs.c",
    "net/wireless/debugfs.h",
    "net/wireless/ethtool.c",
    "net/wireless/ibss.c",
    "net/wireless/Kconfig",
    "net/wireless/lib80211.c",
    "net/wireless/lib80211_crypt_ccmp.c",
    "net/wireless/lib80211_crypt_tkip.c",
    "net/wireless/lib80211_crypt_wep.c",
    "net/wireless/Makefile",
    "net/wireless/mesh.c",
    "net/wireless/mlme.c",
    "net/wireless/nl80211.c",
    "net/wireless/nl80211.h",
    "net/wireless/ocb.c",
    "net/wireless/of.c",
    "net/wireless/pmsr.c",
    "net/wireless/radiotap.c",
    "net/wireless/rdev-ops.h",
    "net/wireless/reg.c",
    "net/wireless/reg.h",
    "net/wireless/scan.c",
    "net/wireless/sme.c",
    "net/wireless/sysfs.c",
    "net/wireless/sysfs.h",
    "net/wireless/tests/chan.c",
    "net/wireless/tests/fragmentation.c",
    "net/wireless/tests/Makefile",
    "net/wireless/tests/module.c",
    "net/wireless/tests/scan.c",
    "net/wireless/tests/util.c",
    "net/wireless/tests/util.h",
    "net/wireless/trace.c",
    "net/wireless/trace.h",
    "net/wireless/util.c",
    "net/wireless/wext-compat.c",
    "net/wireless/wext-compat.h",
    "net/wireless/wext-core.c",
    "net/wireless/wext-priv.c",
    "net/wireless/wext-proc.c",
    "net/wireless/wext-sme.c",
    "net/wireless/wext-spy.c",
    # cfg80211.ko files end
    "drivers/mfd/qcom-pm8008.c",
    "drivers/regulator/qcom-pm8008-regulator.c",
    # mac80211.ko files start
    "net/mac80211/aead_api.c",
    "net/mac80211/aead_api.h",
    "net/mac80211/aes_ccm.h",
    "net/mac80211/aes_cmac.c",
    "net/mac80211/aes_cmac.h",
    "net/mac80211/aes_gcm.h",
    "net/mac80211/aes_gmac.c",
    "net/mac80211/aes_gmac.h",
    "net/mac80211/agg-rx.c",
    "net/mac80211/agg-tx.c",
    "net/mac80211/airtime.c",
    "net/mac80211/cfg.c",
    "net/mac80211/chan.c",
    "net/mac80211/debug.h",
    "net/mac80211/debugfs.c",
    "net/mac80211/debugfs.h",
    "net/mac80211/debugfs_key.c",
    "net/mac80211/debugfs_key.h",
    "net/mac80211/debugfs_netdev.c",
    "net/mac80211/debugfs_netdev.h",
    "net/mac80211/debugfs_sta.c",
    "net/mac80211/debugfs_sta.h",
    "net/mac80211/driver-ops.c",
    "net/mac80211/driver-ops.h",
    "net/mac80211/drop.h",
    "net/mac80211/eht.c",
    "net/mac80211/ethtool.c",
    "net/mac80211/fils_aead.c",
    "net/mac80211/fils_aead.h",
    "net/mac80211/he.c",
    "net/mac80211/ht.c",
    "net/mac80211/ibss.c",
    "net/mac80211/ieee80211_i.h",
    "net/mac80211/iface.c",
    "net/mac80211/key.c",
    "net/mac80211/key.h",
    "net/mac80211/led.c",
    "net/mac80211/led.h",
    "net/mac80211/link.c",
    "net/mac80211/main.c",
    "net/mac80211/mesh.c",
    "net/mac80211/mesh.h",
    "net/mac80211/mesh_hwmp.c",
    "net/mac80211/mesh_pathtbl.c",
    "net/mac80211/mesh_plink.c",
    "net/mac80211/mesh_ps.c",
    "net/mac80211/mesh_sync.c",
    "net/mac80211/michael.c",
    "net/mac80211/michael.h",
    "net/mac80211/mlme.c",
    "net/mac80211/ocb.c",
    "net/mac80211/offchannel.c",
    "net/mac80211/parse.c",
    "net/mac80211/pm.c",
    "net/mac80211/rate.c",
    "net/mac80211/rate.h",
    "net/mac80211/rc80211_minstrel_ht.c",
    "net/mac80211/rc80211_minstrel_ht.h",
    "net/mac80211/rc80211_minstrel_ht_debugfs.c",
    "net/mac80211/rx.c",
    "net/mac80211/s1g.c",
    "net/mac80211/scan.c",
    "net/mac80211/spectmgmt.c",
    "net/mac80211/sta_info.c",
    "net/mac80211/sta_info.h",
    "net/mac80211/status.c",
    "net/mac80211/tdls.c",
    "net/mac80211/tkip.c",
    "net/mac80211/tkip.h",
    "net/mac80211/trace.c",
    "net/mac80211/trace.h",
    "net/mac80211/trace_msg.h",
    "net/mac80211/tx.c",
    "net/mac80211/util.c",
    "net/mac80211/vht.c",
    "net/mac80211/wbrf.c",
    "net/mac80211/wep.c",
    "net/mac80211/wep.h",
    "net/mac80211/wme.c",
    "net/mac80211/wme.h",
    "net/mac80211/wpa.c",
    "net/mac80211/wpa.h",
    # mac80211.ko files end
]

def define_common_upstream_files():
    for file in COPY_FILES:
        copy_file(
            name = "copied-" + file,
            src = "//common:{}".format(file),
            out = file,
        )

    # TODO: Use hermetic_genrule when prebuilt `patch` tool is available.
    native.genrule(
        name = "patched-drivers/regulator/qti_fixed_regulator.c",
        srcs = [
            "//common:drivers/regulator/fixed.c",
            ":drivers/regulator/fixed.diff",
        ],
        outs = ["drivers/regulator/qti_fixed_regulator.c"],
        cmd = "patch --follow-symlinks -o $@ -i $(execpath :drivers/regulator/fixed.diff) $(execpath //common:drivers/regulator/fixed.c)",
    )

    native.genrule(
        name = "patched-drivers/dma/qcom/gpi.c",
        srcs = [
            "//common:drivers/dma/qcom/gpi.c",
            ":drivers/dma/qcom/gpi_fix.diff",
        ],
        outs = ["drivers/dma/qcom/gpi_fixed.c"],
        cmd = "patch --follow-symlinks -o $@ -i $(execpath :drivers/dma/qcom/gpi_fix.diff) $(execpath //common:drivers/dma/qcom/gpi.c)",
    )
